extends SceneTree

const State = preload("res://ProbabilityVision/PlayerKnowledgeState.gd")
const Tracker = preload("res://ProbabilityVision/GameStateTracker.gd")
const HUD = preload("res://ProbabilityVision/ProbabilityHUD.gd")
const Config = preload("res://ProbabilityVision/Config.gd")
const Plugin = preload("res://ProbabilityVision/ProbabilityVisionPlugin.gd")
var checks: int = 0
var failures: Array = []

func check(ok: bool, label: String) -> void:
	checks += 1
	if not ok:
		failures.append(label)
		printerr("FAIL: ", label)

func probability(state, expected: float, label: String) -> void:
	var view = state.snapshot()
	check(view.valid and is_equal_approx(view.next_live_probability, expected), label)
	if view.valid and view.total_remaining > 0:
		check(is_equal_approx(view.next_live_probability + view.next_blank_probability, 1.0), label + " complementary")

func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	var state = State.new()
	state.begin_load(2, 3)
	probability(state, 0.4, "2/5 unknown")
	state.observe(3, true)
	probability(state, 0.25, "phone #3 live: 1/4")
	check(state.snapshot().known_shells == {3: true}, "phone known distinct")
	state.remove_first(false)
	probability(state, 1.0 / 3.0, "beer blank: 1/3")
	check(state.snapshot().known_shells == {2: true}, "beer shifts phone")
	state.remove_first(false)
	probability(state, 1.0, "second removal makes phone first")
	check(state.snapshot().known_shells == {1: true}, "second shift")
	state.invert_first()
	probability(state, 0.0, "known first inverted")
	check(state.snapshot().known_shells == {1: false}, "known type flips")
	check(state.snapshot().live_count_values == [1], "known inverter exact count")
	state.remove_first(false)
	check(state.snapshot().known_shells.is_empty(), "spent known deleted")

	state.begin_load(2, 3)
	state.observe(1, true)
	state.observe(3, false)
	probability(state, 1.0, "known first 100%")
	state.begin_load(2, 3)
	state.observe(1, false)
	probability(state, 0.0, "known first blank 0%")
	state.begin_load(4, 3)
	state.observe(2, false)
	state.observe(4, true)
	state.observe(6, true)
	probability(state, 0.5, "multiple known example")
	state.begin_load(2, 2)
	state.observe(2, true)
	state.observe(3, true)
	probability(state, 0.0, "exclusion proof")
	check(state.snapshot().derived_shells == {1: false, 4: false}, "proof separate from known")

	state.begin_load(2, 3)
	var initial = state.snapshot()
	state.invert_first()
	probability(state, 0.6, "unknown inverter swaps 40/60")
	check(state.snapshot().live_count_values == [1, 3], "inverter counts do not disclose real shell")
	check(state.snapshot().known_shells.is_empty(), "inverter invents no observation")
	check(is_equal_approx(state.snapshot().live_expected, 2.2), "inverter live expectation")
	state.invert_first()
	check(state.snapshot() == initial, "two inverters restore distribution")
	state.invert_first()
	state.remove_first(true)
	probability(state, 0.5, "inverse then public live shot conditions original blank")
	check(state.snapshot().live_count_values == [2], "post-inverter public shot resolves total")
	state.begin_load(2, 3)
	state.observe(3, true)
	state.invert_first()
	probability(state, 0.75, "phone plus inverter")
	state.observe(1, false)
	probability(state, 0.0, "magnifier after inversion conditions")
	check(state.snapshot().live_count_values == [1], "magnifier resolves count branch")

	state.begin_load(2, 3)
	state.observe(3, true)
	state.unknown_reorder()
	probability(state, 0.4, "legal random reorder forgets positions")
	check(state.snapshot().known_shells.is_empty(), "reorder clears known")
	state.invert_first()
	state.unknown_reorder()
	probability(state, 0.44, "uncertain count weights preserved under reorder")
	state.begin_load(0, 3)
	probability(state, 0.0, "all blanks")
	check(state.snapshot().derived_shells.size() == 3, "all blanks derived")
	state.begin_load(3, 0)
	probability(state, 1.0, "all live")
	state.begin_load(1, 0)
	state.remove_first(true)
	check(state.snapshot().valid and state.snapshot().total_remaining == 0, "empty chamber")
	check(state.snapshot().next_live_probability == null, "empty has no fake probability")
	check(not state.remove_first(false) and not state.snapshot().valid, "empty double removal fail closed")
	state.begin_load(2, 3)
	check(not state.observe(6, true), "out of range disclosure fail closed")
	check(not state.snapshot().valid and state.snapshot().known_shells.is_empty(), "invalid cleared")
	state.begin_load(0, 2)
	check(not state.observe(1, true), "contradiction fail closed")
	check(not state.begin_load(-1, 4), "negative counts rejected")
	check(not state.begin_load(17, 0), "unsupported size rejected")
	state.begin_load(2, 3)
	state.observe(3, true)
	state.begin_load(1, 2)
	check(state.snapshot().known_shells.is_empty(), "reload clears old positions")
	probability(state, 1.0 / 3.0, "reload new distribution")

	# Noninterference: differing hidden orders never cross the event boundary.
	var a = Tracker.new()
	var b = Tracker.new()
	var hidden_a = [true, false, true, false, false]
	var hidden_b = [false, true, false, false, true]
	check(hidden_a != hidden_b, "noninterference fixture differs")
	for tracker in [a, b]:
		tracker.handle_event("load_public", {"live": 2, "blank": 3})
		tracker.handle_event("invert", {})
	check(a.snapshot() == b.snapshot(), "same legal information yields same HUD regardless hidden order")
	a.handle_event("reset", {})
	check(not a.snapshot().valid, "scene/round reset pauses")
	b.handle_event("reveal", {"position": "3", "live": true, "source": "phone"})
	check(not b.snapshot().valid, "malformed payload fail closed")
	b.handle_event("load_public", {"live": 2, "blank": 3})
	b.handle_event("reveal", {"position": 1, "live": true, "source": "hidden_chamber"})
	check(not b.snapshot().valid, "unapproved disclosure source rejected")

	var config = Config.read_settings()
	state.begin_load(2, 3)
	state.observe(3, true)
	var text = HUD.render_text(state.snapshot(), config)
	check("25.0%" in text and "75.0%" in text, "HUD formats example")
	check("第3发" in text and "第1发" not in text, "HUD displays only known/derived positions")
	config.decimals = 2
	check("25.00%" in HUD.render_text(state.snapshot(), config), "HUD configurable decimals")
	config.language = "en"
	check("KNOWN" in HUD.render_text(state.snapshot(), config), "English HUD")
	var bad_config = Config.sanitize_settings({"decimals": [], "margin_x": {}, "width": [], "font_size": null, "opacity": NAN, "toggle_key": "NOT_A_KEY", "hud_position": []})
	check(bad_config.decimals == 1 and bad_config.width == 340 and bad_config.font_size == 22, "malformed numeric config uses defaults")
	check(bad_config.margin_x == 28 and is_equal_approx(bad_config.opacity, 0.94), "malformed config and NaN handled")
	check(bad_config.toggle_key == "E" and bad_config.hud_position == "top_left", "bad key and position use defaults")
	check(Config.sanitize_settings({"decimals": 99, "opacity": -1}).decimals == 3, "config values clamped")
	check(Config.sanitize_settings({"decimals": NAN}).decimals == 1, "nonfinite integer config uses default")

	var owner = Node.new()
	root.add_child(owner)
	Plugin.attach(owner, "singleplayer")
	await process_frame
	await process_frame
	var plugin = root.get_node_or_null("ProbabilityVision")
	check(is_instance_valid(plugin), "plugin attaches safely")
	if is_instance_valid(plugin):
		Plugin.emit_event(owner, "load_public", {"live": 2, "blank": 3})
		var old_generation = Plugin.generation(owner)
		Plugin.emit_event(owner, "reset", {})
		Plugin.emit_event(owner, "load_public", {"live": 2, "blank": 3})
		Plugin.emit_event(owner, "reveal", {"position": 1, "live": true, "source": "magnifier", "generation": old_generation})
		check(plugin.tracker.snapshot().known_shells.is_empty(), "stale async observation rejected after reload")
		var outsider = Node.new()
		root.add_child(outsider)
		Plugin.emit_event(outsider, "reveal", {"position": 1, "live": true, "source": "magnifier"})
		check(plugin.tracker.snapshot().known_shells.is_empty(), "events outside owning scene ignored")
		outsider.queue_free()
		check(not plugin.hud.panel.visible, "HUD default hidden")
		var key = InputEventKey.new()
		key.keycode = KEY_E
		key.pressed = true
		plugin._input(key)
		check(plugin.hud.panel.visible, "E shows HUD")
		plugin._input(key)
		check(not plugin.hud.panel.visible, "E hides HUD")
		key.echo = true
		plugin._input(key)
		check(not plugin.hud.panel.visible, "key repeat ignored")
	owner.queue_free()
	await process_frame
	await process_frame
	check(not is_instance_valid(root.get_node_or_null("ProbabilityVision")), "scene exit frees knowledge and HUD")
	print("PROBABILITY_VISION_TESTS ", JSON.stringify({"checks": checks, "failures": failures, "passed": failures.is_empty()}))
	quit(0 if failures.is_empty() else 1)
